version: '3.8'

services:  
  authservice:
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    container_name: auth_service
    restart: always
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=authdb;Username=user;Password=user
    ports:
      - "5002:5002"
    networks:
      - microservices_network

  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    container_name: api_gateway
    restart: always
    environment:
      - AuthService__GrpcUrl=http://authservice:5002
      - DOTNET_SYSTEM_NET_HTTP_SOCKETSHTTPHANDLER_HTTP2SUPPORT=true
    ports:
      - "5000:5000"
    networks:
      - microservices_network

networks:
  microservices_network:
    external: true
